---
all:
  children:
    webservers:
      hosts:
        frontend:
          ansible_host: 127.0.0.1
          ansible_connection: local
    
    backend:
      hosts:
        api:
          ansible_host: 127.0.0.1
          ansible_connection: local
    
    admin:
      hosts:
        admin_panel:
          ansible_host: 127.0.0.1
          ansible_connection: local
    
    localhost_group:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local